name: Jira Release
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract version name
        run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
        id: extract_version_name
      - name: Jira Release
        id: release
        uses: PRNDcompany/jira-release@v1.2
        with:
          domain: 'https://istay-test1.atlassian.net'
          project: 'I20'
          version: BACK-${{ steps.extract_version_name.outputs.version }}
          auth-token: 'a2tpbUBpc3RheS5pbzppVU55ZUNwV1RXR2xuZWs1eXlodEJGMjc='
      - name: Print New Version
        run: |
          echo ${{ steps.release.outputs.new-version }}